#!/usr/bin/env bash
# Thanks Prime for this tmux-sessionizer
# My version with splitting of windows

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/repos -mindepth 1 -maxdepth 2 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -d -s $selected_name -c $selected
    tmux split-window -v -t $selected_name:0 -c $selected
    tmux split-window -h -t $selected_name:0.1 -c $selected
    tmux attach-session -t $selected_name
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    tmux split-window -v -t $selected_name:0 -c $selected
    tmux split-window -h -t $selected_name:0.1 -c $selected
fi

tmux switch-client -t $selected_name
